Stage 1
maxubayter/shop_demo pull request #1
Opened 2018-07-12 16:44 UTC by maxubayter

2018-07-12 21:10 UTC, bluzir requested changes
Нужно поправить

2018-07-12 21:10 UTC, bluzir commented on main.py
> +#############################################
что это за строчка

2018-07-12 21:10 UTC, bluzir commented on main.py
> +    url = "https://api.telegram.org/bot603929717:AAHL0GmBrQko5rXSiddZAvrudsmSflJyEhg/getUpdates"
лишний перенос
токен вынести в отдельную переменную и подставлять уже

2018-07-12 21:10 UTC, bluzir commented on main.py
> +        requests.post("https://api.telegram.org/bot603929717:AAHL0GmBrQko5rXSiddZAvrudsmSflJyEhg/sendMessage", params = {"chat_id" : chat_id, "text" : answer})
тут какой-то косяк с отступами
потерял их

2018-07-12 21:10 UTC, bluzir commented on main.py
> +
тут не нужен отступ

2018-07-12 21:10 UTC, bluzir commented on main.py
> +###############################################
вот это убираем

2018-07-12 21:10 UTC, bluzir commented on main.py
> +        decoded_coin = decoded_coin['ticker']['price'] + " $"
назови тут переменную, чтобы отражала содержание, например `price`

2018-07-12 21:10 UTC, bluzir commented on main.py
> +        decoded_coin = decoded_coin['ticker']['price'] + " $"
тоже самое с названием

2018-07-12 21:10 UTC, bluzir commented on main.py
> +        decoded_coin = "Бот выводит курс криптовалют bitcoin и ethereum с ресурса https://ru.cryptonator.com/. Для получения актуального курса на данный момент времени, введите в чате /btc (для битко
опять, что еще за название переменной?
вынеси текст в понятную переменную наверх файла и бери оттуда

2018-07-12 21:10 UTC, bluzir commented on main.py
> +def currancy(coin):
название функции не отражает содержание
- мы определяем команду для бота
- мы получаем курс

то есть ее можно назвать: `get_rate_by_command`
но вообще я бы вынес запросы к криптонатору в отедльную функцию и вызывал бы ее уже 

а эта функция была просто за определение команды и вызов той функции

задавай вопросы в чате если не понял

2018-07-13 11:17 UTC, maxubayter commented on main.py
> +#############################################
исправил

2018-07-13 11:17 UTC, maxubayter commented on main.py
> +    url = "https://api.telegram.org/bot603929717:AAHL0GmBrQko5rXSiddZAvrudsmSflJyEhg/getUpdates"
исправил

2018-07-13 11:17 UTC, maxubayter commented on main.py
> +        requests.post("https://api.telegram.org/bot603929717:AAHL0GmBrQko5rXSiddZAvrudsmSflJyEhg/sendMessage", params = {"chat_id" : chat_id, "text" : answer})
исправил

2018-07-13 11:17 UTC, maxubayter commented on main.py
> +
исправил

2018-07-13 11:17 UTC, maxubayter commented on main.py
> +###############################################
исправил

2018-07-13 11:17 UTC, maxubayter commented on main.py
> +        decoded_coin = decoded_coin['ticker']['price'] + " $"
исправил

2018-07-13 11:18 UTC, maxubayter commented on main.py
> +        decoded_coin = decoded_coin['ticker']['price'] + " $"
исправил

2018-07-13 11:18 UTC, maxubayter commented on main.py
> +        decoded_coin = "Бот выводит курс криптовалют bitcoin и ethereum с ресурса https://ru.cryptonator.com/. Для получения актуального курса на данный момент времени, введите в чате /btc (для битко
исправил

2018-07-13 11:18 UTC, maxubayter commented on main.py
> +def currancy(coin):
убрал эту функцию и сделал запрос в криптонатор отдельной функцией, которой на вход подается монета

2018-07-13 12:37 UTC, merged